src/objects/BioBriefing__c.object
<CustomObject>
    <fields>
        <fullName>ImageURL__c</fullName>
        <label>ImageURL</label>
        <type>Url</type>
    </fields>
    <label>BioBriefing</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BioBriefings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BioBriefingExtension.cls
public with sharing class BioBriefingExtension {
 public String imageURL{get;set;}
private BioBriefing__c bbObject;

  public BioBriefingExtension(ApexPages.StandardController controller)
  {
  	bbObject = (BioBriefing__c)controller.getRecord();
    imageURL='/servlet/servlet.FileDownload?file=';
    List< Attachment > attachmentList = [select name from Attachment where ParentId=:bbObject.Id];
    if(attachmentList.size()>0)
    {
      imageURL=imageURL+attachmentList[0].id;
      bbObject.ImageURL__c = imageURL;
    }
    else{
    	imageURL = '';
    }
  }
  public PageReference Save()
  {
  	String fileId = '';
    imageURL='/servlet/servlet.FileDownload?file=';
    List<Attachment> attachmentList = [SELECT Id,Name,ContentType FROM Attachment where ParentId =: bbObject.Id Order By LastModifiedDate DESC  LIMIT 1];
       
    if(attachmentList != null && attachmentList.size() > 0)
    {
    	fileId = attachmentList[0].Id;
        imageURL=imageURL+attachmentList[0].id;
    }
    else{
        imageURL = '';
    }
    bbObject.ImageURL__c = imageURL;
    Upsert bbObject;
    return  new ApexPages.StandardController(bbObject).view();
    }
}