src/objects/Campaign_Management__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Num_Sent__c</fullName>
        <label>Num Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Campaign</label>
        <referenceTo>Campaign_Management__c</referenceTo>
        <relationshipLabel>Campaign Management</relationshipLabel>
        <relationshipName>Campaign_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Soft_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Soft Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Un-Planned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Campaign Management</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampaignManagementExtension.cls
public with sharing class CampaignManagementExtension {
	public ID CampaignId {get; set;}
	public Campaign_Management__c campaignObj;
	//private ApexPages.StandardController standardController; // ASK SOURABH
	
	public CampaignManagementExtension(apexpages.standardController controller) {
		Campaign_Management__c campaignRecord=(Campaign_Management__c)controller.getRecord();
		//this.standardController = controller; // ASK SOURABH
     	campaignObj = [SELECT Campaign_Name__c,Category__c,CreatedById,CreatedDate,Description__c,End_Date__c,Id,LastModifiedDate,Name,Num_Sent__c,OwnerId,Parent_Campaign__c,Start_Date__c,Status__c,Type__c FROM Campaign_Management__c WHERE ID= :campaignRecord.Id];
   	}    
   	
    public void softDeleteRecord(){
    	//ApexPages.StandardController controller
    	CampaignId = campaignObj.id; 
        //CampaignId = controller.getId();
        campaignObj = [Select Campaign_Name__c,Category__c,Soft_Deleted__c,Name FROM Campaign_Management__c WHERE ID= :CampaignId];
        campaignObj.Soft_Deleted__c = true;
        update campaignObj;
   	}
   	public void copyRecord(){
   		Campaign_Management__c copy = campaignObj.clone();
   		insert copy;
   	}
}