src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Entry</label>
        <referenceTo>Time_Entries__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Items</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entries__c.object
<CustomObject>
    <fields>
        <fullName>Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoiced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Entries</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestInvoiceExtension.cls
@isTest
public with sharing class TestInvoiceExtension {
    public static testMethod void testInvoiceExtensionSearchClientProjects() {
    	TestData.insertAccount();
    	TestData.insertProjectForAccount();
    	Invoice__c invoiceObj = new Invoice__c();
    	
    	List<Account> accountList = new List<Account>([Select ID from Account]);
    	invoiceObj.Account__c = accountList.size() > 0 ? accountList[0].Id : null;
	 	
		//CALLING CONTROLLER SEARCH METHOD
        InvoiceExtension controller = new InvoiceExtension(new ApexPages.StandardController(invoiceObj));
        controller.searchClientProjects();

        //System.assertEquals(listBeforeCopy.size() + 1,listAfterCopy.size());
    }
    public static testMethod void testInvoiceExtensionGenerateInvoice() {
    	//CREATING TEST DATA
    	TestData.insertAccount();
    	TestData.insertProjectForAccount();
		TestData.insertContactDependingOnAccounts(1);
    	TestData.insertTimeEntries();
    	
    	Invoice__c invoiceObj = new Invoice__c();
    	
    	List<Account> accountList = new List<Account>([Select ID from Account]);
    	invoiceObj.Account__c = accountList.size() > 0 ? accountList[0].Id : null;
	 	
		//CALLING CONTROLLER SEARCH METHOD
        InvoiceExtension controller = new InvoiceExtension(new ApexPages.StandardController(invoiceObj));
        controller.searchClientProjects();       
        List<Project__c> projectList = controller.getProjects();
        controller.generateInvoice();
        List<Time_Entries__c> timeEntryList = new List<Time_Entries__c>([Select Id,Invoiced__c from Time_Entries__c where Project__C IN :projectList AND Invoiced__c = false]);
        List<Invoice__c> invoiceNewList = new List<Invoice__c>([Select Id from Invoice__c where Account__c =: invoiceObj.Account__c]);        
		for(Time_Entries__c timeEntryObj :timeEntryList){
			List<Invoice_Line_Items__c> invoiceLineItemList = new List<Invoice_Line_Items__c>([Select Id, Time_Entry__c from Invoice_Line_Items__c where Time_Entry__c =: timeEntryObj.Id]);
			System.assertEquals(timeEntryObj.Invoiced__c,true);
			System.assertEquals(invoiceLineItemList.size(),1);
		}        
    }      
}