src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_End_Date__c</fullName>
        <label>Invoice End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Start_Date__c</fullName>
        <label>Invoice Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Hrs__c</fullName>
        <label>Invoice Hrs</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Entry</label>
        <referenceTo>Time_Entries__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Items</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Invoiced_Hrs__c</fullName>
        <label>Total Invoiced Hrs</label>
        <summarizedField>Time_Entries__c.Duration__c</summarizedField>
        <summaryFilterItems>
            <field>Time_Entries__c.Invoiced__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Time_Entries__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Project_Hrs__c</fullName>
        <label>Total Project Hrs</label>
        <summarizedField>Time_Entries__c.Duration__c</summarizedField>
        <summaryForeignKey>Time_Entries__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entries__c.object
<CustomObject>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <formula>Duration__c  *  Contact__r.Bill_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoiced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Entries</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceExtension.cls
public with sharing class InvoiceExtension {
    
    private final Invoice__c InvoiceObj;
	List<Project__c> projects;
	List<Project__c> selectedProjects = new List<Project__c>();
	
	public InvoiceExtension(apexpages.standardController controller){
		InvoiceObj=(Invoice__c)controller.getRecord();
		Date startDate = System.Date.today().toStartOfMonth(); 
		Date endDate = startDate.addMonths(1).addDays(-1);
        InvoiceObj.Invoice_Start_Date__c = startDate;
        InvoiceObj.Invoice_End_Date__c = endDate;
    }
    public List<Project__c> getProjects() {
      //  if(projects == null) projects = [SELECT Account__c,End_Date__c,Id,Name,Start_Date__c,Total_Invoiced_Hrs__c,Selected__c,Total_Project_Hrs__c FROM Project__c LIMIT 10];
        return projects;
    }
    // public PageReference getSelected()
    //{
       // selectedAccounts.clear();
        //for(accountwrapper accwrapper : accountList)
        //if(accwrapper.selected == true)
       // selectedAccounts.add(accwrapper.acc);
      //  return null;
    //}
    public PageReference searchClientProjects(){
    	//Invoice__c currentInvoice =(Invoice__c)controller.getRecord();
    	projects = [SELECT Account__c,End_Date__c,Id,Name,Start_Date__c,Total_Invoiced_Hrs__c,Selected__c,Total_Project_Hrs__c FROM Project__c  WHERE Account__c =: InvoiceObj.Account__c  LIMIT 10];
    	//projects = [SELECT Account__c,End_Date__c,Id,Name,Start_Date__c,Total_Invoiced_Hrs__c,Selected__c,Total_Project_Hrs__c FROM Project__c WHERE Account__c =: InvoiceObj.Account__c AND Start_Date__c >=: InvoiceObj.Invoice_Start_Date__c AND End_Date__c <=: InvoiceObj.Invoice_End_Date__c];
    	return null;
    }
    public PageReference generateInvoice(){
    	List<Invoice__c> InvoiceList = new List<Invoice__c>();
        
                
    	Invoice__c newInvoiceObj;
    	for(Project__c projectObj: projects)
    	{
    		newInvoiceObj  = new Invoice__c();
    		newInvoiceObj = InvoiceObj.clone();
    		newInvoiceObj.Name = 'Invoice for Project - ' + projectObj.Name;
    		newInvoiceObj.Project__c = projectObj.Id;
    		InvoiceList.Add(newInvoiceObj);
    	}
    	insert InvoiceList;
        
        List<Invoice_Line_Items__c> InvoiceLineItemList = new List<Invoice_Line_Items__c>();
    	List<Time_Entries__c> TimeEntryList = new List<Time_Entries__c>();
    	List<Time_Entries__c> TimeEntryListToUpdate = new List<Time_Entries__c>();
    
        for(Invoice__c invoiceObj : InvoiceList){
        	TimeEntryList = [SELECT Billable_Amount__c,Contact__c,Date__c,Description__c,Duration__c,Id,Invoiced__c,Name,Project__c FROM Time_Entries__c WHERE Project__C =: invoiceObj.Project__c];
    		for(Time_Entries__c timeEntryObj:TimeEntryList)
    		{
    			Invoice_Line_Items__c invoiceLineItemsObj = new Invoice_Line_Items__c();
    			invoiceLineItemsObj.Name = invoiceObj.Name + ' - Line Item';
	    		invoiceLineItemsObj.Invoice__c = invoiceObj.Id;
    			invoiceLineItemsObj.Invoice_Amount__c = timeEntryObj.Billable_Amount__c;
    			invoiceLineItemsObj.Invoice_Hrs__c = timeEntryObj.Duration__c;
    			invoiceLineItemsObj.Time_Entry__c = timeEntryObj.Id;
    			invoiceLineItemsObj.Entry_Date__c = timeEntryObj.Date__c;
    			invoiceLineItemsObj.Description__c = timeEntryObj.Description__c;
    			InvoiceLineItemList.Add(invoiceLineItemsObj);
    			
    			timeEntryObj.Invoiced__c = true;
    			TimeEntryListToUpdate.Add(timeEntryObj);
    		}
    	}
    	System.debug(InvoiceLineItemList);
    	insert InvoiceLineItemList;
    	update TimeEntryListToUpdate;
    	
		return null;
    }
}