src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Hrs__c</fullName>
        <label>Invoice Hrs</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Entry</label>
        <referenceTo>Time_Entries__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Items</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entries__c.object
<CustomObject>
    <fields>
        <fullName>Billable_Amount__c</fullName>
        <formula>Duration__c  *  Contact__r.Bill_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoiced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Entries</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TR_InvoiceRelatedTimeEntriesHandler.cls
public with sharing class TR_InvoiceRelatedTimeEntriesHandler {
    public static void InitiateProcess(List<Invoice__c> InvoiceList){
    	System.debug(InvoiceList);
    	List<Time_Entries__c> TimeEntryList = new List<Time_Entries__c>();
    	List<Invoice_Line_Items__c> some = GetInvoiceLineItems(InvoiceList);
    	System.debug('SOME ' + some);
    	TimeEntryList = GetInvoiceTimeEntries(some);
    	update TimeEntryList;
    }
    public static List<Invoice_Line_Items__c> GetInvoiceLineItems(List<Invoice__c> InvoiceList){
    	List<Invoice_Line_Items__c> InvoiceLineItemList;
    	List<Invoice_Line_Items__c> InvoiceLineItemListToRetrive = new List<Invoice_Line_Items__c>();
    	
    	for(Invoice__c invoiceObj : InvoiceList){
    		InvoiceLineItemList = new List<Invoice_Line_Items__c>();
    		InvoiceLineItemList = [SELECT Description__c,Entry_Date__c,Id,Invoice_Amount__c,Invoice_Hrs__c,Invoice__c,Name,Time_Entry__c FROM Invoice_Line_Items__c WHERE Invoice__c =: invoiceObj.Id];
    		InvoiceLineItemListToRetrive.AddAll(InvoiceLineItemList);
    	}
    	return InvoiceLineItemListToRetrive;
    }
    public static List<Time_Entries__c> GetInvoiceTimeEntries(List<Invoice_Line_Items__c> InvoiceLineItemList){
    	Time_Entries__c timeEntryObj;
    	List<Time_Entries__c> TimeEntryList = new List<Time_Entries__c>();
    	for(Invoice_Line_Items__c invoiceLineItmeObj : InvoiceLineItemList){
    		timeEntryObj = new Time_Entries__c();
    		System.debug('Invoice Line items ' + invoiceLineItmeObj);
    		timeEntryObj = [SELECT Billable_Amount__c,Contact__c,Date__c,Description__c,Duration__c,Id,Invoiced__c,Name,Project__c FROM Time_Entries__c WHERE Id=: invoiceLineItmeObj.Time_Entry__c];
    		System.debug('Time entry Obj ' + timeEntryObj);
    		
    		timeEntryObj.Invoiced__c = false;
    		TimeEntryList.Add(timeEntryObj);    		
    	}
    	return TimeEntryList;
    }
}