src/objects/Languages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Languages</label>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>H_S_C__c</fullName>
        <label>H.S.C %</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S_S_C__c</fullName>
        <label>S.S.C %</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Title</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student_Header__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student Header</label>
</CustomObject>

src/classes/StudentRegistrationExtension.cls
public with sharing class StudentRegistrationExtension {
    private final Student__c studentObj;
    public string SelectedLanguage {get; set;}

    
    public StudentRegistrationExtension(apexpages.standardController controller){
    	ApexPages.Message notification;
    	try{
    		studentObj=(Student__c)controller.getRecord();
    		studentObj.Student_Name__c = 'SAMPLE';
    		studentObj.H_S_C__c = 100;
    		studentObj.S_S_C__c = 100;
    		studentObj.Roll_Number__c = 123;
    	}
        catch(Exception e){
        	notification = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while storing student details - '+e.getMessage());
            ApexPages.addMessage(notification);
        } 
    }
    /*public void RetriveHeader(){
    	ApexPages.Message notification;
    	try{
			Map<String, Student_Header__c> header = Student_Header__c.getAll();
			Map<String, String> allheader = new Map<String,String>();
			for(Student_Header__c headerValue : header.values()){
				allheader.put(headerValue.Language__c,headerValue.Name);
			}
			if(SelectedLanguage != null && SelectedLanguage != ''){
				allheader.get(SelectedLanguage).Name;
			}
			else{
				StudentHeader = allheader.get('en_US').Name;
			}
    	}
        catch(Exception e){
        	notification = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while retriving student header - '+e.getMessage());
            ApexPages.addMessage(notification);
        } 
    }*/
    public void submitStudentDetails(){
    	ApexPages.Message notification;
    	try{
    		if(studentObj != null){
    			insert studentObj;
    			if(studentObj.Id != null){
    				notification = new ApexPages.Message(ApexPages.severity.CONFIRM,'Your admission application has been submitted successfully. Reference Id is - ' + studentObj.Id);
            		ApexPages.addMessage(notification);
    			}
    		}
    	}
        catch(Exception e){
        	notification = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while storing student details - '+e.getMessage());
            ApexPages.addMessage(notification);
        } 
    }
     public List<SelectOption> getLanguageList() {
    	List<SelectOption> options = new List<SelectOption>();
    	try{
        //options.add(new SelectOption('', 'Select'));        
        Map<String, Languages__c> languages = Languages__c.getAll();
        
        //SORTING BY NAME - NOT NEEDED - EXTRA FUNCTIONALITY
        List<String> sortinglanguages = new List<String>();
        sortinglanguages.addAll(languages.keySet());
        sortinglanguages.sort();
        
        for (String languageName : sortinglanguages) {
            Languages__c lang = languages.get(languageName);
            options.add(new SelectOption(lang.Language_Code__c, lang.Name));
        }
        }
        catch(Exception e){
        	ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while getting languages list '+e.getMessage());
            ApexPages.addMessage(errormsg);
        }  
        return options;
    }
    public void languageCheckAction() {
    	System.debug('Selected Language'+SelectedLanguage);
    }
}