src/objects/TimeZoneDetails__c.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <label>Area Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TimeZoneDetail</label>
    <nameField>
        <displayFormat>TZ-{0000}</displayFormat>
        <label>TimeZoneDetails Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeZoneDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Query.cls
public with sharing class Query {
    public static Map<String, TimeZoneDetails__c> getTimeZoneDetailsWithKeyAreaCodeInMap(){
        List<TimeZoneDetails__c> tzList = new List<TimeZoneDetails__c>([SELECT ID,State__c,Time_Zone__c,Area_Code__c from TimeZoneDetails__c]);
		Map<String, TimeZoneDetails__c> tzMap=new Map<String, TimeZoneDetails__c>();
		for (TimeZoneDetails__c tzObj : tzList)
		{
        	tzMap.put(tzObj.Area_Code__c, tzObj); 
		}
        return tzMap;
    }
}